// F64b — `xgg device partitions <did>` readout for partition occupancy sensors.
//
// Background (see survey notes, F64b prompt). Mi-Home's web UI shows partition
// labels "A-1".."B-16" on the multi-zone occupancy sensor (32 zones). The
// labels are NOT generated by the gateway — they come from the public
// miot-spec cloud endpoint `instance/v2/multiLanguage?urn=<urn>` which
// publishes a `service:NNN -> "A-1"` table. We hard-code the equivalent
// positional schema here to keep the CLI offline:
//
//   row = floor((siid - 4) / 16) → ["A","B"][row]
//   col = ((siid - 4) % 16) + 1  → 1..16
//
// Domain: siid 4..35 (32 partitions). siid 36 on this device is the
// indicator light, NOT a partition. Other services (siid 1-3) are device
// info / sensor overall status / sensor config, also not partitions.
//
// Currently this geometry is verified only for `xiaomi.sensor_occupy.p1`.
// Other partition-capable models (e.g. `izq.sensor_occupy.trio`) ship
// different spec layouts and need their own verification before we
// extend the allowlist.

import type { DeviceSpec, MiotService } from '../schemas/device-spec.js';
import { getDeviceSpec } from '../usecases/get-device-spec.js';
import { getDevice } from './devices.js';
import type { ResourceDeps } from './index.js';

// Models whose spec follows the 2×16 partition layout (siid 4..35).
// Conservatively narrow — adding a new model requires verifying the spec
// against the multiLanguage cloud table first (see survey notes).
const PARTITION_MODEL_ALLOWLIST: ReadonlySet<string> = new Set(['xiaomi.sensor_occupy.p1']);

const PARTITION_SIID_MIN = 4;
const PARTITION_SIID_MAX = 35;
const PARTITION_ROW_WIDTH = 16;
const PARTITION_ROW_LABELS = ['A', 'B'] as const;

export interface DevicePartition {
  siid: number;
  label: string;
  serviceDescription: string;
  propsCount: number;
}

/**
 * True iff `siid` lies inside the 2×16 partition range (4..35) for a known
 * partition-supporting model. The model gate is essential: siid 4 on a
 * thermometer is NOT "A-1", it's just service #4.
 */
export function isPartitionSiid(model: string, siid: number): boolean {
  if (!PARTITION_MODEL_ALLOWLIST.has(model)) return false;
  return siid >= PARTITION_SIID_MIN && siid <= PARTITION_SIID_MAX;
}

/**
 * Map a partition siid to its display label. Returns `undefined` when the
 * siid is outside the partition range, OR when the model is not in the
 * allowlist. Caller decides whether to fall back to the bare service
 * description.
 */
export function partitionLabel(model: string, siid: number): string | undefined {
  if (!isPartitionSiid(model, siid)) return undefined;
  const offset = siid - PARTITION_SIID_MIN;
  const rowIdx = Math.floor(offset / PARTITION_ROW_WIDTH);
  const col = (offset % PARTITION_ROW_WIDTH) + 1;
  const row = PARTITION_ROW_LABELS[rowIdx];
  if (row === undefined) return undefined;
  return `${row}-${col}`;
}

/**
 * Returns the partition list for a device. Empty array when the device's
 * model is not in the partition allowlist. Each entry carries the synthesized
 * label and the service's MIoT description + properties count.
 */
export async function getDevicePartitions(
  did: string,
  deps: ResourceDeps,
): Promise<DevicePartition[]> {
  const device = await getDevice(did, deps);
  if (!PARTITION_MODEL_ALLOWLIST.has(device.model)) return [];
  const spec = await getDeviceSpec(device.urn, {
    ...(deps.timeoutMs !== undefined && { timeoutMs: deps.timeoutMs }),
  });
  return partitionsFromSpec(device.model, spec);
}

/**
 * Pure-data variant. Splits out from getDevicePartitions so callers that
 * already hold the spec (e.g. the ambiguity-error injection in rules.ts) can
 * re-use the same mapping without a second network round-trip.
 */
export function partitionsFromSpec(model: string, spec: DeviceSpec): DevicePartition[] {
  if (!PARTITION_MODEL_ALLOWLIST.has(model)) return [];
  const out: DevicePartition[] = [];
  for (const svc of spec.services) {
    const label = partitionLabel(model, svc.iid);
    if (label === undefined) continue;
    out.push({
      siid: svc.iid,
      label,
      serviceDescription: svc.description,
      propsCount: svc.properties?.length ?? 0,
    });
  }
  return out;
}

/**
 * F64b — annotate a service description with its partition label when the
 * service belongs to a partition-capable device.
 *
 *   service description "Partition Occupancy Sensor"
 *   + model xiaomi.sensor_occupy.p1, siid=7
 *   → "Partition Occupancy Sensor (A-4)"
 *
 * Non-partition device or out-of-range siid → returns the description
 * unchanged. This is the function the property-resolver ambiguity error
 * uses to enrich each candidate line.
 */
export function annotateServiceDescription(
  model: string,
  service: Pick<MiotService, 'iid' | 'description'>,
): string {
  const label = partitionLabel(model, service.iid);
  if (label === undefined) return service.description;
  return `${service.description} (${label})`;
}

/** Exposed for tests + diagnostics. Mutating returned set has no effect. */
export function partitionModelAllowlist(): ReadonlySet<string> {
  return PARTITION_MODEL_ALLOWLIST;
}
